Non-Admin Users CanNOT Access Driver List
ucsb-cs156-s24/proj-gauchoride-s24-5pm-6 pull request #20
Opened 2024-05-17 01:19 UTC by amisra0

Anika - Non-admin users now get FORBIDDEN error when trying to access driver list from Swagger UI endpoint.
running npm test and npm run coverage is still 100, everything seems to work and now if you log in as a non-admin user and try to get list of all drivers you will get a 403 FORBIDDEN error. But if you login from an admin account you should get 200 signal and a list of all drivers. So now non-admin users don't have access.

2024-05-17 05:39 UTC, yuji-sakaguchi approved these changes, later dismissed
LGTM

2024-05-17 20:34 UTC, pconrad requested changes
I'd like to see a test for this in `src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriversControllerTests.java`  

It might look similar to this existing test:

```java
 @Test
  public void users__logged_out_all() throws Exception {
    mockMvc.perform(get("/api/drivers/all"))
        .andExpect(status().is(403));
  }
```


But instead of testing what happens when the user is logged out, it might use the `   @WithMockUser(roles = { "USER" })` annotation. 

You could write the test, then briefly revert the code to the old line, i.e. 
```
@PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_DRIVER') || hasRole('ROLE_USER')")
```
and the test should fail.  Then put in your new line 
```java
@PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_DRIVER')")
```

and the test should pass.

2024-05-17 20:34 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_DRIVER')")
I wonder why there isn't a test for these two cases?

That is: a test that shows that a user that is not a driver and is not an admin gets a 403 Forbidden error when trying to access this endpoint?

2024-05-18 21:47 UTC, amisra0 commented on src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriversController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') || hasRole('ROLE_DRIVER')")
Thank you for the suggestion professor. I have added a test to ensure that a user role gets a 403 error in DriversControllerTests.java

2024-05-23 05:10 UTC, yuji-sakaguchi approved these changes
LGTM

2024-05-24 01:41 UTC, pconrad approved these changes
LGTM

2024-05-24 01:41 UTC, merged