Yuji RiderNavBar Updates
ucsb-cs156-s24/proj-gauchoride-s24-5pm-6 pull request #24
Opened 2024-05-20 06:58 UTC by yuji-sakaguchi

Fixed bug where not riders can access dropdown for Shifts and Drivers Page button on the navbar. 
Made changes to the test file to make sure shifts and drivers page navbar buttons are hidden for riders. 
Made additional edits to navbar for adminOnly users so all the required information is shown.
Made sure admin users with multiple roles won't have duplicate navbar buttons.

Closes #9 

New Riders User (No more Shifts, Drivers Page)
![image](https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/assets/92128100/fff6ee1f-001b-4db6-81ff-4a490a18acb4)

New AdminOnly User (Added Shifts Availability as part of Shifts Dropdown, Drivers Page)
![image](https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-6/assets/92128100/a73a6c21-c710-4c71-95ad-e4729c82c457)

2024-05-21 00:35 UTC, lindseywn submitted a review, later dismissed
LGTM, functioning properly and tests are all passing

2024-05-22 02:44 UTC, diyaparm approved these changes, later dismissed
LGTM

2024-05-25 22:56 UTC, pconrad requested changes
Two small suggestions for simplifying the code:

2024-05-25 22:56 UTC, pconrad commented on frontend/src/main/components/Nav/AppNavbar.js
> +                (hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_ADMIN")) && isParticipant(currentUser) && (
The `isPartcipant(currentUser)` part is redundant if I'm not mistaken.
Couldn't we just say:
```suggestion
                (hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_ADMIN"))  (
```

2024-05-25 22:56 UTC, pconrad commented on frontend/src/main/components/Nav/AppNavbar.js
> +                (hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_ADMIN")) && isParticipant(currentUser) && (
Couldn't we just do:

```suggestion
                (hasRole(currentUser, "ROLE_DRIVER") || hasRole(currentUser, "ROLE_ADMIN")) (
```

2024-05-25 23:12 UTC, pconrad requested changes
A couple of small changes to suggest, then this looks good to me.

2024-05-25 23:49 UTC, pconrad approved these changes
LGTM

2024-05-25 23:50 UTC, merged