liz - sort users table by default
ucsb-cs156-s24/proj-gauchoride-s24-5pm-6 pull request #26
Opened 2024-05-22 00:50 UTC by andyinnie

2024-05-22 05:24 UTC, lindseywn submitted a review, later dismissed
LGTM, works properly according to acceptance criteria, tests pass as well

2024-05-25 23:55 UTC, pconrad requested changes
Tested on dokku and works as promised; code is good!

Just one thing.. could we remove that one commented out line (even though it isn't from you?)

2024-05-25 23:55 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
>      //const columnsToDisplay = showButtons ? buttonColumn : columns;
Can we remove this comment out line? 

I know it isn't from you, but when we see these in files we touch, it's good to get rid of them.

2024-05-25 23:55 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
>      //const columnsToDisplay = showButtons ? buttonColumn : columns;
See also: 

https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-05-29 00:12 UTC, diyaparm reviewed
LGTM removed comments that was requested.

2024-05-30 17:11 UTC, pconrad approved these changes
LGTM!

2024-05-30 17:11 UTC, merged